# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: "^lib/"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=1024"]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: local
    hooks:
      - id: mypy
        name: Type-check Python with mypy
        language: python
        types: [python]
        entry: mypy
        args: ["--config-file=pyproject.toml"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.2
    hooks:
      - id: ruff
        name: Lint Python with Ruff
        args: [--fix, --config=pyproject.toml]
      - id: ruff-format
        name: Format Python with Ruff
        args: [--config=pyproject.toml]
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v9.18.0"
    hooks:
      - id: eslint
        name: Lint ECMAScript with eslint
        args: ["--config", "./eslint.config.mjs"]
        additional_dependencies:
          - eslint@9.16.0
          - eslint-plugin-prettier@5.2.1
          - eslint-plugin-tailwindcss@3.17.5
          - eslint-plugin-react@7.37.2
          - typescript-eslint@8.17.0
