#cloud-config

packages:
  # Services
  - certbot
  - nginx
  - postgresql
  - python3-certbot-nginx
  # Utilities
  - multitail
  - neovim
  - tree
  - zsh

write_files:
  - path: /etc/environment
    content: |
      FQDN="${fqdn}"
      DJANGO_SETTINGS_MODULE="hpk.settings.dev"
      DB_NAME="${db_name}"
      DB_USER="${db_user}"
      DB_PASSWORD="${db_password}"
    append: true

users:
  - name: wagtail
    uid: 1500
  - name: ada
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKUDDwkurpZbeUCdQRGDO1uxQt7kedRbm/f67mARtPeC hipikat@lemon-2024-08-29
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    groups: sudo, wagtail
    shell: /bin/zsh

runcmd:
  # TODO: Run certbot to obtain SSL certs & setup for automatic renewal

  # Install ada's dotfiles
  - sudo -u ada git clone https://github.com/hipikat/dotfiles.git /home/ada/.dotfiles
  - sudo -u ada sh -c 'cd /home/ada/.dotfiles && sh install_dotfiles.sh'
  - sudo chmod 755 /home/ada

  # Install Just
  - >-
    curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh |
    bash -s -- --to /usr/local/bin

  # Install UV
  - >-
    curl -LsSf https://astral.sh/uv/install.sh |
    UV_UNMANAGED_INSTALL="/usr/local/bin" HOME="/root" sh

  # Install Node
  - >-
    . /etc/environment &&
    wget -qO- https://nodejs.org/dist/v${node_version}/node-v${node_version}-linux-x64.tar.xz |
    tar -xJ -C /usr/local/
  - mv /usr/local/node-v${node_version}-linux-x64 /usr/local/node-v${node_version}
  - ln -s /usr/local/node-v${node_version}/bin/node /usr/local/bin/node
  - ln -s /usr/local/node-v${node_version}/bin/npm /usr/local/bin/npm

  # Clone the project into /app and create initially-empty directories
  - git clone https://github.com/hipikat/hpk.io.git /app
  - mkdir -p /app/logs /app/media

  # Ensure /app/** is owned by wagtail, is group-writable, and new files inherit the group
  - chown -R wagtail:wagtail /app
  - chmod -R g+rw /app
  - find /app -type d -exec chmod g+s {} \;

  # Assuage git's concerns about ownership under /app
  # - git config --global --add safe.directory /app

  # Install project dependencies
  - sudo -u wagtail uv sync --directory /app -v --no-progress
  - cd /app && sudo -u wagtail npm install --no-audit --no-fund --no-progress --loglevel=info

  # Create the database and run migrations
  - just -f /app/Justfile db-init ${db_password}
  - sudo -u wagtail source /etc/environment && just -f /app/Justfile dj migrate

  # Create the Django superuser
  - sudo -u wagtail source /etc/environment && just -f /app/Justfile dj-createsuperuser ${admin_django_user} ${admin_email} ${admin_password}
  - sudo -u wagtail just -f /app/Justfile dj-createsuperuser ${admin_django_user} ${admin_email} ${admin_password}

  # Build artifacts and collect all static files
  - cd /app && sudo -u wagtail npm run build

  # Enable systemd journal services
  - mkdir -p /var/log/journal
  - systemctl restart systemd-journald

  # Configure and start Gunicorn
  - ln -s /app/config/gunicorn-dev.service.ini /etc/systemd/system/gunicorn-hpk.service
  - ln -s /app/config/gunicorn.socket.ini /etc/systemd/system/gunicorn-hpk.socket
  - systemctl start gunicorn-hpk.socket && systemctl status gunicorn-hpk.socket

  # Configure and start Nginx
  - echo '\nenv FQDN;' | sudo tee -a /etc/nginx/nginx.conf
  - rm -f /etc/nginx/sites-enabled/default
  - ln -s /app/config/nginx-site-dev.conf /etc/nginx/sites-available/hpk
  - ln -s /etc/nginx/sites-available/hpk /etc/nginx/sites-enabled/hpk
  - systemctl restart nginx

final_message: "The system has been initialised with cloud-init!"
