#cloud-config

packages:
  # Ops
  - just
  # Services
  - certbot
  - gunicorn
  - nginx
  - postgresql
  - python3-certbot-nginx
  # Utilities
  - neovim
  - tree
  - zsh

write_files:
- path: /etc/environment
  content: |
    NODE_VERSION="20.17.0"
  append: true

users:
  - name: wagtail
    uid: 1500
  - name: ada
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKUDDwkurpZbeUCdQRGDO1uxQt7kedRbm/f67mARtPeC hipikat@lemon-2024-08-29
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo, wagtail
    shell: /bin/zsh

runcmd:
  # TODO: Run certbot to obtain SSL certs & setup for automatic renewal

  # Install ada's dotfiles
  - sudo -u ada git clone https://github.com/hipikat/dotfiles.git /home/ada/.dotfiles
  - sudo -u ada sh -c 'cd /home/ada/.dotfiles && sh install_dotfiles.sh'

  # Install Just
  - |
    curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | \
    bash -s -- --to /usr/local/bin

  # Install UV
  - |
    curl -LsSf https://astral.sh/uv/install.sh | \
    env UV_UNMANAGED_INSTALL="/usr/local/bin" HOME="/root" sudo -E sh

  # Install Node
  - |
    . /etc/environment && \
    wget -qO- https://nodejs.org/dist/v${NODE_VERSION}/node-v${NODE_VERSION}-linux-x64.tar.xz | \
    tar -xJ -C /usr/local/
  - mv /usr/local/node-v${NODE_VERSION}-linux-x64 /usr/local/node-v${NODE_VERSION}
  - ln -s /usr/local/node-v${NODE_VERSION}/bin/node /usr/local/bin/node
  - ln -s /usr/local/node-v${NODE_VERSION}/bin/npm /usr/local/bin/npm

  # Checkout the project and install dependencies
  - mkdir -p /app
  - chown root:wagtail /app
  - chmod 775 /app
  - sudo -u wagtail sh -c '\
      git clone https://github.com/hipikat/hpk.io.git /app && \
      cd /app && \
      nohup uv sync -v --no-progress > /var/log/uv_sync.log 2>%1 & \
      nohup npm install --no-audit --no-fund --no-progress --loglevel=info > /var/log/npm_install.log 2>&1 &'

  # TODO: run migrations, collect static files, build aftifacts

  # TODO: configure & start PostgreSQL

  # TODO: configure & start gunicorn
  - ln -s /app/config/gunicorn.service.ini /etc/systemd/system/gunicorn-hpkio.service
  - ln -s /app/config/gunicorn.socket.ini /etc/systemd/system/gunicorn-hpkio.socket

  # TODO: run migrations etc.

  # TODO: configure & start nginx

final_message: "The system has been initialised with cloud-init-dev.yml!"
