#cloud-config

packages:
  - just
  - zsh
  - tree

write_files:
- path: /etc/environment
  content: |
    NODE_VERSION="20.17.0"
  append: true

users:
  - name: wagtail
    uid: 1500
  - name: ada
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKUDDwkurpZbeUCdQRGDO1uxQt7kedRbm/f67mARtPeC hipikat@lemon-2024-08-29
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo, wagtail
    shell: /bin/zsh

runcmd:
  # Install ada's dotfiles
  - sudo -u ada git clone https://github.com/hipikat/dotfiles.git /home/ada/.dotfiles
  - sudo -u ada sh -c 'cd /home/ada/.dotfiles && sh install_dotfiles.sh'

  # Install Node.js (LTS) globally
  - |
    . /etc/environment && \
    wget -qO- https://nodejs.org/dist/v${NODE_VERSION}/node-v${NODE_VERSION}-linux-x64.tar.xz | \
    tar -xJ -C /usr/local/
  - mv /usr/local/node-v${NODE_VERSION}-linux-x64 /usr/local/node-v${NODE_VERSION}
  - ln -s /usr/local/node-v${NODE_VERSION}/bin/node /usr/local/bin/node
  - ln -s /usr/local/node-v${NODE_VERSION}/bin/npm /usr/local/bin/npm

  # Checkout the project
  - mkdir -p /app
  - chown root:wagtail /app
  - chmod 775 /app
  - sudo -u wagtail git clone https://github.com/hipikat/hpk.io.git /app

final_message: "The system has been initialised with cloud-init-override.yml!"
